//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("GongSolutions.WPF.DragDrop 1.1.0.0")]
[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("GongSolutions.WPF.DragDrop 1.1.0")]
[assembly: AssemblyCopyright("Copyright © GongSolutions.WPF.DragDrop 2013 - 2017")]

